config/routes.rb
Rails.application.routes.draw do
  resources :check_ins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "check_ins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
    has_rich_text :remarks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :set_check_in, only: %i[ show edit update destroy ]

  # GET /check_ins or /check_ins.json
  def index
    @check_ins = CheckIn.all
  end

  # GET /check_ins/1 or /check_ins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @check_in = CheckIn.new
    @time = Time.new.strftime("%Y-%m-%d %H:%M")
  end

  # GET /check_ins/1/edit
  def edit
  end

  # POST /check_ins or /check_ins.json
  def create
    @check_in = CheckIn.new(check_in_params)

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to check_in_url(@check_in), notice: "Check in was successfully created." }
        format.json { render :show, status: :created, location: @check_in }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_ins/1 or /check_ins/1.json
  def update
    respond_to do |format|
      if @check_in.update(check_in_params)
        format.html { redirect_to check_in_url(@check_in), notice: "Check in was successfully updated." }
        format.json { render :show, status: :ok, location: @check_in }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1 or /check_ins/1.json
  def destroy
    @check_in.destroy

    respond_to do |format|
      format.html { redirect_to check_ins_url, notice: "Check in was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in
      @check_in = CheckIn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def check_in_params
      params.require(:check_in).permit(:luggage_num, :name, :room_num, :people_num, :received_date_time, :received_by, :checkout_date_time, :checkout_by, :remarks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/check_ins/_check_in.html.erb
<div id="<%= dom_id check_in %>">
  <p>
    <strong>Luggage num:</strong>
    <%= check_in.luggage_num %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= check_in.name %>
  </p>

  <p>
    <strong>Room num:</strong>
    <%= check_in.room_num %>
  </p>

  <p>
    <strong>People num:</strong>
    <%= check_in.people_num %>
  </p>

  <p>
    <strong>Received date time:</strong>
    <%= check_in.received_date_time %>
  </p>

  <p>
    <strong>Received by:</strong>
    <%= check_in.received_by %>
  </p>

  <p>
    <strong>Checkout date time:</strong>
    <%= check_in.checkout_date_time %>
  </p>

  <p>
    <strong>Checkout by:</strong>
    <%= check_in.checkout_by %>
  </p>

  <p>
    <strong>Remarks:</strong>
    <%= check_in.remarks %>
  </p>

</div>

app/views/check_ins/_form.html.erb
<%= form_with(model: check_in) do |form| %>
  <% if check_in.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
        <% check_in.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :luggage_num, style: "display: block" %>
    <%= form.number_field :luggage_num %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :room_num, style: "display: block" %>
    <%= form.number_field :room_num %>
  </div>

  <div>
    <%= form.label :people_num, style: "display: block" %>
    <%= form.number_field :people_num %>
  </div>

  <div>
    <%= form.label :received_date_time, style: "display: block" %>
    <%= form.datetime_field :received_date_time, value: @time %>
  </div>

  <div>
    <%= form.label :received_by, style: "display: block" %>
    <%= form.text_field :received_by %>
  </div>

  <div>
    <%= form.label :checkout_date_time, style: "display: block" %>
    <%= form.datetime_field :checkout_date_time, value: @time %>
  </div>

  <div>
    <%= form.label :checkout_by, style: "display: block" %>
    <%= form.text_field :checkout_by %>
  </div>

  <div>
    <%= form.label :remarks, style: "display: block" %>
    <%= form.rich_text_area :remarks %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/check_ins/edit.html.erb
<h1>Editing check in</h1>

<%= render "form", check_in: @check_in %>

<br>

<div>
  <%= link_to "Show this check in", @check_in %> |
  <%= link_to "Back to check ins", check_ins_path %>
</div>

app/views/check_ins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Check ins</h1>

<div >
  
  
    
    
  
</div>

<%= link_to "New check in", new_check_in_path %>


<div class="table-responsive" id="check_ins">
  <table class="table table-primary">
    <thead>
      <tr>
        <% CheckIn.column_names.each do |c| %>
          <th scope="col"><%= c %></th>
        <%end%>   
      </tr>
    </thead>
    <tbody>
      <% @check_ins.each do |check_in| %>
      <tr class="">
        <td scope="row"><%= check_in.id %></td>
        <td scope="row"><%= check_in.luggage_num %></td>
        <td scope="row"><%= check_in.name %></td>
        <td scope="row"><%= check_in.room_num %></td>
        <td scope="row"><%= check_in.people_num %></td>
        <td scope="row"><%= check_in.received_date_time.strftime("%Y/%m/%d %H:%M") %></td>
        <td scope="row"><%= check_in.received_by %></td>
        <td scope="row"><%= check_in.checkout_date_time.strftime("%Y/%m/%d %H:%M") %></td>
        <td scope="row"><%= check_in.checkout_by %></td>
        <td scope="row"><%= check_in.remarks %></td>
        <td scope="row"><%= check_in.created_at.strftime("%Y/%m/%d %H:%M") %></td>
        <td scope="row"><%= check_in.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
        <td><%= link_to "Show this check in", check_in %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/check_ins/new.html.erb
<h1>New check in</h1>

<%= render "form", check_in: @check_in %>

<br>

<div>
  <%= link_to "Back to check ins", check_ins_path %>
</div>

app/views/check_ins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @check_in %>

<div>
  <%= link_to "Edit this check in", edit_check_in_path(@check_in) %> |
  <%= link_to "Back to check ins", check_ins_path %>

  <%= button_to "Destroy this check in", @check_in, method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>